#!/usr/bin/env bash
#pings an lp address passed as an arg.

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]\.{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	ping -c 5 "$1"
else
	echo "usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
