#!/bin/bash

# Define signal handlers
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; exit' SIGTERM SIGQUIT

# Get the current PID and save it to the file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
done

