#!/usr/bin/env bash

# This script generates an RSA key pair with a passphrase.

# Set the key file name
key_name="school"

# Set the number of bits
bits=4096

# Set the passphrase
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $bits -f ~/.ssh/$key_name -N $passphrase

# Print a message indicating successful key generation
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $key_name."
echo "Your public key has been saved in $key_name.pub."

